 all: STDFooPlot.exe
 STDFooPlot.exe:
	 g++ -msse3 -O3 -Wall -Wextra -Wno-cast-function-type -pedantic -Wno-unused-parameter -Wfatal-errors -DNDEBUG -o STDFooPlot.exe -mwindows -I. -I../../fltk-1.3.8 -static -O STDFooPlot.cpp ../../fltk-1.3.8/lib/libfltk.a -lole32 -luuid -lcomctl32
.PHONY: STDFooPlot.exe
